#!/usr/bin/env python3
"""Embeds the example skin into the DLL: writes src/ui/skin_example.inc.

The DLL writes these files into "<Win64>\\UUEPBS Skins\\" the first time that folder is made.
Run after changing anything in skins/Example - Midnight Rose (see gen_example_skin.py).
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
NAME = "Example - Midnight Rose"
SRC = os.path.normpath(os.path.join(HERE, "..", "..", "..", "skins", NAME))
OUT = os.path.normpath(os.path.join(HERE, "..", "src", "ui", "skin_example.inc"))

files = []
for dirpath, _, names in os.walk(SRC):
    for n in sorted(names):
        full = os.path.join(dirpath, n)
        files.append((os.path.relpath(full, SRC).replace("\\\\", "/").replace(os.sep, "/"), open(full, "rb").read()))
files.sort()

lines = ["// Generated by tools/gen_skin_inc.py from skins/" + NAME + " - do not edit.",
         'const char* const kExampleSkinName = "' + NAME + '";']
for i, (path, data) in enumerate(files):
    lines.append("const unsigned char kExampleFile%d[] = {" % i)
    for k in range(0, len(data), 24):
        lines.append("    " + ", ".join("0x%02x" % b for b in data[k:k + 24]) + ",")
    lines.append("};")
lines.append("const EmbeddedFile kExampleSkinFiles[] = {")
for i, (path, data) in enumerate(files):
    lines.append('    {"%s", kExampleFile%d, sizeof(kExampleFile%d)},' % (path, i, i))
lines.append("};")
with open(OUT, "w", newline="\n") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", OUT, "-", len(files), "files,", sum(len(d) for _, d in files) // 1024, "KB")
