"""Regenerates src/core/bone_dictionary_default.inc from Scripts/BoneDictionary.json.
Run after editing the shipped dictionary so the DLL's built-in copy matches:
    python tools/gen_dictionary_inc.py
"""
import json, os, sys
here = os.path.dirname(os.path.abspath(__file__))
src = os.path.join(here, "..", "..", "..", "mod", "UUEPBS", "Scripts", "BoneDictionary.json")
dst = os.path.join(here, "..", "src", "core", "bone_dictionary_default.inc")
text = open(src, encoding="utf-8").read()
json.loads(text)  # must be valid
chunks = [text[i:i + 3000] for i in range(0, len(text), 3000)]  # MSVC limits one literal piece to ~16 KB
with open(dst, "w", encoding="utf-8", newline="\n") as f:
    f.write("// Generated by tools/gen_dictionary_inc.py from Scripts/BoneDictionary.json - do not edit.\n")
    for c in chunks:
        assert ")UBSD\"" not in c
        f.write('R"UBSD(' + c + ')UBSD"\n')
print("wrote", dst, len(text), "bytes in", len(chunks), "pieces")
