#include "skin.hpp"

#include "../core/json.hpp"
#include "../core/presets.hpp" // path_from_utf8 / path_to_utf8

#include <imgui_internal.h> // RegisterUserTexture / UnregisterUserTexture

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <optional>
#include <set>
#include <sstream>
#include <system_error>

namespace fs = std::filesystem;

namespace uuepbs::ui
{
    namespace
    {
        using json::JsonReader;
        using json::JsonValue;

        // Example skin written into a new skins folder (generated by tools/gen_skin_inc.py).
        struct EmbeddedFile
        {
            const char* path;
            const unsigned char* data;
            size_t size;
        };
#include "skin_example.inc"

        std::string lower(std::string_view s)
        {
            std::string out(s);
            for (char& c : out)
            {
                if (c >= 'A' && c <= 'Z')
                {
                    c = static_cast<char>(c - 'A' + 'a');
                }
            }
            return out;
        }

        // ---------------------------------------------------------------- colours
        struct ColorSlot
        {
            const char* key;
            int col;          // ImGuiCol_ or -1 (role only)
            ImVec4 value;     // default
            const char* ref;  // default copies this (earlier) key instead
            bool keep;        // default: leave Dear ImGui's dark theme colour alone
        };

        // The built-in look. Keep in step with the README in the skins folder.
        const ColorSlot kColorSlots[] = {
            {"accent", -1, {0.91f, 0.44f, 0.66f, 1.0f}, nullptr, false},
            {"accent_dim", -1, {0.60f, 0.28f, 0.44f, 1.0f}, nullptr, false},
            {"good", -1, {0.45f, 0.85f, 0.55f, 1.0f}, nullptr, false},
            {"warn", -1, {0.98f, 0.72f, 0.30f, 1.0f}, nullptr, false},
            {"muted", -1, {0.62f, 0.62f, 0.68f, 1.0f}, nullptr, false},
            {"title", -1, {}, "accent", false},
            {"text", ImGuiCol_Text, {1.0f, 1.0f, 1.0f, 1.0f}, nullptr, false},
            {"text_disabled", ImGuiCol_TextDisabled, {0.50f, 0.50f, 0.50f, 1.0f}, nullptr, false},
            {"window", ImGuiCol_WindowBg, {0.085f, 0.085f, 0.105f, 1.0f}, nullptr, false},
            {"panel", ImGuiCol_ChildBg, {0.105f, 0.105f, 0.130f, 1.0f}, nullptr, false},
            {"popup", ImGuiCol_PopupBg, {0.110f, 0.110f, 0.140f, 0.98f}, nullptr, false},
            {"border", ImGuiCol_Border, {0.22f, 0.22f, 0.28f, 1.0f}, nullptr, false},
            {"frame", ImGuiCol_FrameBg, {0.160f, 0.160f, 0.200f, 1.0f}, nullptr, false},
            {"frame_hover", ImGuiCol_FrameBgHovered, {0.210f, 0.200f, 0.260f, 1.0f}, nullptr, false},
            {"frame_active", ImGuiCol_FrameBgActive, {0.250f, 0.220f, 0.300f, 1.0f}, nullptr, false},
            {"title_bg", ImGuiCol_TitleBg, {}, "window", false},
            {"title_bg_active", ImGuiCol_TitleBgActive, {}, "window", false},
            {"slider_grab", ImGuiCol_SliderGrab, {}, "accent", false},
            {"slider_grab_active", ImGuiCol_SliderGrabActive, {1.0f, 0.60f, 0.78f, 1.0f}, nullptr, false},
            {"check", ImGuiCol_CheckMark, {}, "accent", false},
            {"button", ImGuiCol_Button, {0.20f, 0.19f, 0.25f, 1.0f}, nullptr, false},
            {"button_hover", ImGuiCol_ButtonHovered, {}, "accent_dim", false},
            {"button_active", ImGuiCol_ButtonActive, {}, "accent", false},
            {"header", ImGuiCol_Header, {0.26f, 0.18f, 0.25f, 1.0f}, nullptr, false},
            {"header_hover", ImGuiCol_HeaderHovered, {0.36f, 0.22f, 0.32f, 1.0f}, nullptr, false},
            {"header_active", ImGuiCol_HeaderActive, {}, "accent_dim", false},
            {"tab", ImGuiCol_Tab, {0.14f, 0.14f, 0.18f, 1.0f}, nullptr, false},
            {"tab_hover", ImGuiCol_TabHovered, {}, "accent_dim", false},
            {"tab_active", ImGuiCol_TabSelected, {0.34f, 0.20f, 0.30f, 1.0f}, nullptr, false},
            {"separator", ImGuiCol_Separator, {0.24f, 0.24f, 0.30f, 1.0f}, nullptr, false},
            {"text_selected", ImGuiCol_TextSelectedBg, {0.60f, 0.28f, 0.44f, 0.45f}, nullptr, false},
            {"scrollbar_bg", ImGuiCol_ScrollbarBg, {}, nullptr, true},
            {"scrollbar_grab", ImGuiCol_ScrollbarGrab, {}, nullptr, true},
            {"scrollbar_grab_hover", ImGuiCol_ScrollbarGrabHovered, {}, nullptr, true},
            {"scrollbar_grab_active", ImGuiCol_ScrollbarGrabActive, {}, nullptr, true},
        };

        // ---------------------------------------------------------------- sizes
        struct StyleSlot
        {
            const char* key;
            float ImGuiStyle::*scalar;
            ImVec2 ImGuiStyle::*vec;
            ImVec2 value;
            bool keep; // default: leave Dear ImGui's value alone
        };

        const StyleSlot kStyleSlots[] = {
            {"window_rounding", &ImGuiStyle::WindowRounding, nullptr, {0.0f, 0.0f}, false},
            {"child_rounding", &ImGuiStyle::ChildRounding, nullptr, {6.0f, 6.0f}, false},
            {"frame_rounding", &ImGuiStyle::FrameRounding, nullptr, {5.0f, 5.0f}, false},
            {"popup_rounding", &ImGuiStyle::PopupRounding, nullptr, {6.0f, 6.0f}, false},
            {"grab_rounding", &ImGuiStyle::GrabRounding, nullptr, {3.0f, 3.0f}, false},
            {"tab_rounding", &ImGuiStyle::TabRounding, nullptr, {5.0f, 5.0f}, false},
            {"scrollbar_rounding", &ImGuiStyle::ScrollbarRounding, nullptr, {8.0f, 8.0f}, false},
            {"scrollbar_size", &ImGuiStyle::ScrollbarSize, nullptr, {}, true},
            {"grab_min_size", &ImGuiStyle::GrabMinSize, nullptr, {10.0f, 10.0f}, false},
            {"window_border", &ImGuiStyle::WindowBorderSize, nullptr, {0.0f, 0.0f}, false},
            {"child_border", &ImGuiStyle::ChildBorderSize, nullptr, {1.0f, 1.0f}, false},
            {"frame_border", &ImGuiStyle::FrameBorderSize, nullptr, {0.0f, 0.0f}, false},
            {"popup_border", &ImGuiStyle::PopupBorderSize, nullptr, {}, true},
            {"tab_border", &ImGuiStyle::TabBorderSize, nullptr, {}, true},
            {"window_padding", nullptr, &ImGuiStyle::WindowPadding, {14.0f, 12.0f}, false},
            {"frame_padding", nullptr, &ImGuiStyle::FramePadding, {9.0f, 6.0f}, false},
            {"item_spacing", nullptr, &ImGuiStyle::ItemSpacing, {9.0f, 7.0f}, false},
            {"item_inner_spacing", nullptr, &ImGuiStyle::ItemInnerSpacing, {}, true},
        };

        const char* const kImageKeys[] = {"background", "header",      "logo",          "panel",       "button",       "button_hover",
                                          "button_active", "slider_track", "slider_fill", "slider_grab", "slider_grab_active", "checkbox",
                                          "checkbox_checked", "tab",    "tab_hover",     "tab_active"};
        const char* const kExtraStyleKeys[] = {"font_scale", "logo_height"};

        bool known_image_key(std::string_view key)
        {
            for (const char* k : kImageKeys)
            {
                if (key == k)
                {
                    return true;
                }
            }
            return false;
        }

        int hex_digit(char c)
        {
            if (c >= '0' && c <= '9')
                return c - '0';
            if (c >= 'a' && c <= 'f')
                return c - 'a' + 10;
            if (c >= 'A' && c <= 'F')
                return c - 'A' + 10;
            return -1;
        }

        bool color_of(const JsonValue& v, ImVec4& out)
        {
            if (v.kind == JsonValue::Kind::String)
            {
                return parse_color(v.text, out);
            }
            if (v.kind == JsonValue::Kind::Array && (v.items.size() == 3 || v.items.size() == 4))
            {
                float c[4] = {0, 0, 0, 1};
                bool any_big = false;
                for (size_t i = 0; i < v.items.size(); ++i)
                {
                    if (v.items[i].kind != JsonValue::Kind::Number)
                    {
                        return false;
                    }
                    c[i] = static_cast<float>(v.items[i].number);
                    any_big = any_big || c[i] > 1.0f;
                }
                for (int i = 0; i < 4; ++i)
                {
                    if (any_big && (i < 3 || v.items.size() == 4)) // 0..255 notation
                    {
                        c[i] = (i == 3 && v.items.size() == 3) ? 1.0f : c[i] / 255.0f;
                    }
                    c[i] = std::clamp(c[i], 0.0f, 1.0f);
                }
                out = ImVec4(c[0], c[1], c[2], c[3]);
                return true;
            }
            return false;
        }

        bool image_of(const JsonValue& v, SkinImageSpec& out, std::string& why)
        {
            if (v.kind == JsonValue::Kind::String)
            {
                out.file = v.text;
                return !out.file.empty();
            }
            if (v.kind != JsonValue::Kind::Object)
            {
                why = "must be a file name or { \"file\": ... }";
                return false;
            }
            const JsonValue* f = v.find("file");
            if (!f || f->kind != JsonValue::Kind::String || f->text.empty())
            {
                why = "has no \"file\"";
                return false;
            }
            out.file = f->text;
            if (const JsonValue* m = v.find("mode"); m && m->kind == JsonValue::Kind::String)
            {
                const std::string mode = lower(m->text);
                static const std::pair<const char*, ImageMode> modes[] = {{"stretch", ImageMode::Stretch}, {"cover", ImageMode::Cover},
                                                                          {"contain", ImageMode::Contain}, {"fit", ImageMode::Contain},
                                                                          {"center", ImageMode::Center},   {"centre", ImageMode::Center},
                                                                          {"tile", ImageMode::Tile},       {"nine", ImageMode::Nine},
                                                                          {"nine-slice", ImageMode::Nine}, {"9slice", ImageMode::Nine}};
                bool found = false;
                for (const auto& [name, mode_value] : modes)
                {
                    if (mode == name)
                    {
                        out.mode = mode_value;
                        out.has_mode = found = true;
                    }
                }
                if (!found)
                {
                    why = "unknown mode \"" + m->text + "\" (stretch, cover, contain, center, tile or nine)";
                    return false;
                }
            }
            if (const JsonValue* s = v.find("slice"))
            {
                if (s->kind == JsonValue::Kind::Number)
                {
                    out.slice[0] = out.slice[1] = out.slice[2] = out.slice[3] = static_cast<float>(std::max(0.0, s->number));
                }
                else if (s->kind == JsonValue::Kind::Array && (s->items.size() == 4 || s->items.size() == 2))
                {
                    for (size_t i = 0; i < 4; ++i)
                    {
                        const JsonValue& item = s->items[s->items.size() == 2 ? i % 2 : i];
                        out.slice[i] = item.kind == JsonValue::Kind::Number ? static_cast<float>(std::max(0.0, item.number)) : 0.0f;
                    }
                }
                if (!out.has_mode)
                {
                    out.mode = ImageMode::Nine;
                    out.has_mode = true;
                }
            }
            if (const JsonValue* t = v.find("tint"))
            {
                if (!color_of(*t, out.tint))
                {
                    why = "has an unreadable \"tint\"";
                    return false;
                }
            }
            if (const JsonValue* sc = v.find("scale"); sc && sc->kind == JsonValue::Kind::Number && sc->number > 0.01)
            {
                out.scale = static_cast<float>(std::min(sc->number, 16.0));
            }
            return true;
        }

        ImageMode default_mode(std::string_view key)
        {
            if (key == "background")
                return ImageMode::Cover;
            if (key == "logo" || key == "slider_grab" || key == "slider_grab_active" || key.starts_with("icon."))
                return ImageMode::Contain;
            return ImageMode::Stretch;
        }

        // A file name from skin.json must stay inside the skin's folder.
        bool safe_relative(const std::string& file)
        {
            // Checked the same way on every OS: no drive letters or streams (':'), no leading
            // slash, no ".." part, with either kind of slash.
            if (file.empty() || file.find(':') != std::string::npos || file[0] == '/' || file[0] == '\\')
            {
                return false;
            }
            std::string unified = file;
            std::replace(unified.begin(), unified.end(), '\\', '/');
            size_t start = 0;
            while (start <= unified.size())
            {
                const size_t end = std::min(unified.find('/', start), unified.size());
                if (unified.compare(start, end - start, "..") == 0)
                {
                    return false;
                }
                start = end + 1;
            }
            const fs::path p = path_from_utf8(file);
            if (p.empty() || p.is_absolute() || p.has_root_name() || p.has_root_directory())
            {
                return false;
            }
            for (const fs::path& part : p.lexically_normal())
            {
                if (part == "..")
                {
                    return false;
                }
            }
            return true;
        }

        ImTextureData* make_texture(const Rgba8Image& img)
        {
            auto* tex = IM_NEW(ImTextureData)();
            tex->Create(ImTextureFormat_RGBA32, img.width, img.height);
            std::memcpy(tex->Pixels, img.pixels.data(), img.pixels.size());
            tex->UseColors = true;
            tex->RefCount = 1;
            tex->UsedRect = {0, 0, static_cast<unsigned short>(img.width), static_cast<unsigned short>(img.height)};
            tex->SetStatus(ImTextureStatus_WantCreate); // a fresh ImTextureData starts as "OK"
            ImGui::RegisterUserTexture(tex);
            return tex;
        }

        float snap(float v)
        {
            return std::floor(v + 0.5f);
        }

        ImU32 tint_color(const ImVec4& tint, float alpha)
        {
            return ImGui::ColorConvertFloat4ToU32(ImVec4(tint.x, tint.y, tint.z, tint.w * alpha));
        }

        std::mutex g_request_lock;
        std::optional<std::pair<std::string, bool>> g_request;
        std::string g_active{Skin::kBuiltinName};

        const char* const kReadme = R"(UUEPBS window skins
===================

Each sub-folder here is one skin: a skin.json plus PNG or JPG images. Pick a skin in the
window (Status tab > Window skin) or with the console command "ubs skin <name>";
"ubs skin" lists them. Skins change the look only (colours, sizes, images, icons, font),
never the layout. Anything a skin leaves out keeps the built-in look, and an image that
cannot be loaded falls back to the normal widget (the Status tab lists the problem).
The window reloads the active skin by itself when you save skin.json or an image.

Only use skins from people you trust: the images are decoded inside the game process.
Limits: PNG or JPG, at most 4096 x 4096 pixels and 32 MB per file (bigger than 2048 is
scaled down). File names are relative to the skin folder and cannot leave it.

skin.json
---------
{
  "format": "UUEPBS skin",
  "version": 1,
  "name": "My Skin",
  "author": "me",

  "colors": {                // "#RGB", "#RGBA", "#RRGGBB", "#RRGGBBAA" or [r, g, b, a]
    "accent": "#E870A8",     // highlights, edited sliders, title
    "accent_dim": "#99476F", // hovered buttons and tabs
    "good": "#73D98C", "warn": "#FAB84D", "muted": "#9E9EAD",
    "title": "#E870A8",      // the UUEPBS title (defaults to accent)
    "text": "#FFFFFF", "text_disabled": "#808080",
    "window": "#16161B",     // window background (also the clear colour)
    "panel": "#1B1B21",      // lists and editor areas
    "popup": "#1C1C24FA", "border": "#383847", "separator": "#3D3D4D",
    "frame": "#292933", "frame_hover": "#363342", "frame_active": "#40384D",
    "button": "#333040", "button_hover": "=accent_dim", "button_active": "=accent",
    "slider_grab": "=accent", "slider_grab_active": "#FF99C7", "check": "=accent",
    "header": "#422E40", "header_hover": "#5C3852", "header_active": "=accent_dim",
    "tab": "#24242E", "tab_hover": "=accent_dim", "tab_active": "#57334D",
    "text_selected": "#99477073",
    "scrollbar_bg": "...", "scrollbar_grab": "...", "scrollbar_grab_hover": "...", "scrollbar_grab_active": "..."
  },
  ("=name" values above only show what each colour copies when a skin leaves it out;
   write real colours in your skin.)

  "imgui": { "ResizeGrip": "#00000000" },   // any Dear ImGui colour by name (advanced)

  "style": {                 // sizes in pixels at 100% scaling; one number or [x, y]
    "frame_rounding": 5, "child_rounding": 6, "popup_rounding": 6, "grab_rounding": 3,
    "tab_rounding": 5, "scrollbar_rounding": 8, "window_rounding": 0,
    "scrollbar_size": 14, "grab_min_size": 10,
    "window_border": 0, "child_border": 1, "frame_border": 0, "popup_border": 1, "tab_border": 0,
    "window_padding": [14, 12], "frame_padding": [9, 6], "item_spacing": [9, 7], "item_inner_spacing": [4, 4],
    "font_scale": 1.0,       // multiplies config.lua FontSize
    "logo_height": 1.6       // logo height in text lines
  },

  "font": "MyFont.ttf",      // optional TTF/OTF in the skin folder

  "images": {                // a file name, or { "file", "mode", "slice", "tint", "scale" }
    "background":  { "file": "background.jpg", "mode": "cover", "tint": "#FFFFFFB0" },
    "header":      { "file": "header.png", "mode": "nine", "slice": 12 },
    "logo":        "logo.png",
    "panel":       { "file": "panel.png", "slice": 10 },
    "button":      { "file": "button.png", "slice": 8 },
    "button_hover":  { "file": "button_hover.png", "slice": 8 },
    "button_active": { "file": "button_active.png", "slice": 8 },
    "slider_track":  { "file": "track.png", "slice": [8, 6, 8, 6] },
    "slider_fill":   { "file": "fill.png", "slice": [8, 6, 8, 6] },
    "slider_grab":   "grab.png",
    "slider_grab_active": "grab_active.png",
    "checkbox":      "check_off.png",
    "checkbox_checked": "check_on.png",
    "tab":         { "file": "tab.png", "slice": 8 },
    "tab_hover":   { "file": "tab_hover.png", "slice": 8 },
    "tab_active":  { "file": "tab_active.png", "slice": 8 }
  },

  "icons": {                 // square-ish images, drawn at text height
    "simplified": "icons/body.png", "detailed": "icons/bones.png",
    "presets": "icons/presets.png", "status": "icons/status.png",
    "bones": "...", "morphs": "...",
    "reset": "...", "xyz": "...", "refresh": "...", "save": "...", "load": "...",
    "delete": "...", "folder": "...",
    "group.Thighs": "icons/thighs.png"   // any Simplified Panel slider, by its title
  }
}

Image modes
-----------
  stretch  fill the area (default for most images)
  cover    fill the area, keep the aspect ratio, crop the overflow (default for background)
  contain  fit inside the area, keep the aspect ratio (default for logo, grab and icons)
  center   original size (times "scale"), centred
  tile     repeat at original size (times "scale")
  nine     nine-slice: the corners keep their size, the edges and centre stretch.
           "slice": [left, top, right, bottom] in image pixels, or one number for all four.
           Giving "slice" alone implies "nine".
"tint" multiplies the image (its alpha fades it). "scale" sizes corners, tiles and centred
images (1 = image pixels at 100% window scaling).

Start from the example skin next to this file and change what you like.
)";
    } // namespace

    // ==================================================================== parsing

    bool parse_color(std::string_view text, ImVec4& out)
    {
        std::string_view s = text;
        while (!s.empty() && s.front() == ' ')
            s.remove_prefix(1);
        while (!s.empty() && s.back() == ' ')
            s.remove_suffix(1);
        if (s.empty() || s.front() != '#')
        {
            return false;
        }
        s.remove_prefix(1);
        int v[8];
        for (size_t i = 0; i < s.size(); ++i)
        {
            if (i >= 8 || (v[i] = hex_digit(s[i])) < 0)
            {
                return false;
            }
        }
        float c[4] = {0, 0, 0, 1};
        if (s.size() == 3 || s.size() == 4)
        {
            for (size_t i = 0; i < s.size(); ++i)
            {
                c[i] = static_cast<float>(v[i] * 17) / 255.0f;
            }
        }
        else if (s.size() == 6 || s.size() == 8)
        {
            for (size_t i = 0; i < s.size() / 2; ++i)
            {
                c[i] = static_cast<float>(v[i * 2] * 16 + v[i * 2 + 1]) / 255.0f;
            }
        }
        else
        {
            return false;
        }
        out = ImVec4(c[0], c[1], c[2], c[3]);
        return true;
    }

    bool parse_skin(const std::string& text, SkinSpec& out, std::string& message, std::vector<std::string>* warnings)
    {
        out = {};
        JsonValue root;
        if (!JsonReader(text).read(root, message))
        {
            message = "skin.json is not valid JSON: " + message;
            return false;
        }
        if (root.kind != JsonValue::Kind::Object)
        {
            message = "skin.json must be a JSON object { ... }";
            return false;
        }
        auto warn = [&](const std::string& w) {
            if (warnings)
            {
                warnings->push_back(w);
            }
        };
        auto text_of = [&](const char* key) {
            const JsonValue* v = root.find(key);
            return v && v->kind == JsonValue::Kind::String ? v->text : std::string();
        };
        out.name = text_of("name");
        out.author = text_of("author");
        out.description = text_of("description");
        out.font = text_of("font");

        if (const JsonValue* colors = root.find("colors"); colors && colors->kind == JsonValue::Kind::Object)
        {
            for (const auto& [key, v] : colors->members)
            {
                const std::string k = lower(key);
                const bool known = std::any_of(std::begin(kColorSlots), std::end(kColorSlots), [&](const ColorSlot& s) { return k == s.key; });
                ImVec4 c;
                if (!known)
                {
                    warn("colors: unknown key \"" + key + "\"");
                }
                else if (!color_of(v, c))
                {
                    warn("colors: \"" + key + "\" is not a colour like \"#E870A8\"");
                }
                else
                {
                    out.colors[k] = c;
                }
            }
        }
        if (const JsonValue* raw = root.find("imgui"); raw && raw->kind == JsonValue::Kind::Object)
        {
            for (const auto& [key, v] : raw->members)
            {
                ImVec4 c;
                if (color_of(v, c))
                {
                    out.imgui_colors[lower(key)] = c;
                }
                else
                {
                    warn("imgui: \"" + key + "\" is not a colour");
                }
            }
        }
        if (const JsonValue* style = root.find("style"); style && style->kind == JsonValue::Kind::Object)
        {
            for (const auto& [key, v] : style->members)
            {
                const std::string k = lower(key);
                const bool known = std::any_of(std::begin(kStyleSlots), std::end(kStyleSlots), [&](const StyleSlot& s) { return k == s.key; }) ||
                                   std::any_of(std::begin(kExtraStyleKeys), std::end(kExtraStyleKeys), [&](const char* s) { return k == s; });
                if (!known)
                {
                    warn("style: unknown key \"" + key + "\"");
                    continue;
                }
                if (v.kind == JsonValue::Kind::Number)
                {
                    out.style[k] = ImVec2(static_cast<float>(v.number), static_cast<float>(v.number));
                }
                else if (v.kind == JsonValue::Kind::Array && v.items.size() == 2 && v.items[0].kind == JsonValue::Kind::Number &&
                         v.items[1].kind == JsonValue::Kind::Number)
                {
                    out.style[k] = ImVec2(static_cast<float>(v.items[0].number), static_cast<float>(v.items[1].number));
                }
                else
                {
                    warn("style: \"" + key + "\" must be a number or [x, y]");
                }
            }
        }
        auto read_images = [&](const JsonValue* section, const char* prefix, bool icons) {
            if (!section)
            {
                return;
            }
            if (section->kind != JsonValue::Kind::Object)
            {
                warn(std::string(icons ? "icons" : "images") + " must be an object { ... }");
                return;
            }
            for (const auto& [key, v] : section->members)
            {
                const std::string k = std::string(prefix) + lower(key);
                if (!icons && !known_image_key(k))
                {
                    warn("images: unknown key \"" + key + "\"");
                    continue;
                }
                SkinImageSpec img;
                std::string why;
                if (!image_of(v, img, why))
                {
                    warn(std::string(icons ? "icons" : "images") + ": \"" + key + "\" " + why);
                    continue;
                }
                if (!safe_relative(img.file))
                {
                    warn(std::string(icons ? "icons" : "images") + ": \"" + key + "\" must name a file inside the skin folder");
                    continue;
                }
                if (!img.has_mode)
                {
                    img.mode = default_mode(k);
                }
                out.images[k] = img;
            }
        };
        read_images(root.find("images"), "", false);
        read_images(root.find("icons"), "icon.", true);
        message = "ok";
        return true;
    }

    // ==================================================================== Skin

    Skin& skin()
    {
        static Skin instance;
        return instance;
    }

    Skin::~Skin()
    {
        // Only memory is left at this point (the window thread calls shutdown() before the context goes).
        for (ImTextureData* t : m_textures)
        {
            IM_DELETE(t);
        }
        for (ImTextureData* t : m_retired)
        {
            IM_DELETE(t);
        }
    }

    void Skin::request(const std::string& name, bool remember_it)
    {
        std::lock_guard guard(g_request_lock);
        g_request = std::make_pair(name, remember_it);
    }

    std::string Skin::active_name()
    {
        std::lock_guard guard(g_request_lock);
        return g_active;
    }

    std::vector<std::string> Skin::list(const fs::path& folder)
    {
        std::vector<std::string> names;
        std::error_code ec;
        if (folder.empty() || !fs::is_directory(folder, ec))
        {
            return names;
        }
        for (fs::directory_iterator it(folder, ec), end; !ec && it != end; it.increment(ec))
        {
            std::error_code e2;
            if (it->is_directory(e2) && fs::exists(it->path() / "skin.json", e2))
            {
                names.push_back(path_to_utf8(it->path().filename()));
            }
        }
        std::sort(names.begin(), names.end(), [](const std::string& a, const std::string& b) { return lower(a) < lower(b); });
        return names;
    }

    void Skin::set_folder(fs::path folder, const std::string& fallback_skin)
    {
        m_folder = std::move(folder);
        std::error_code ec;
        const bool fresh = !m_folder.empty() && !fs::exists(m_folder, ec);
        if (!m_folder.empty())
        {
            fs::create_directories(m_folder, ec);
        }
        m_folder_ready = !m_folder.empty() && fs::is_directory(m_folder, ec);
        if (m_folder_ready)
        {
            write_readme();
            if (fresh)
            {
                install_example();
            }
        }
        const std::string saved = remembered();
        request(saved.empty() ? fallback_skin : saved, false);
    }

    void Skin::write_readme() const
    {
        std::error_code ec;
        const fs::path file = m_folder / "README.txt";
        std::string existing;
        {
            std::ifstream in(file, std::ios::binary);
            if (in)
            {
                std::ostringstream ss;
                ss << in.rdbuf();
                existing = ss.str();
            }
        }
        if (existing == kReadme)
        {
            return;
        }
        std::ofstream out(file, std::ios::binary | std::ios::trunc);
        out << kReadme;
    }

    void Skin::install_example() const
    {
        std::error_code ec;
        const fs::path base = m_folder / path_from_utf8(kExampleSkinName);
        if (fs::exists(base, ec))
        {
            return;
        }
        for (const EmbeddedFile& f : kExampleSkinFiles)
        {
            const fs::path target = base / path_from_utf8(f.path);
            fs::create_directories(target.parent_path(), ec);
            std::ofstream out(target, std::ios::binary | std::ios::trunc);
            out.write(reinterpret_cast<const char*>(f.data), static_cast<std::streamsize>(f.size));
        }
    }

    void Skin::remember(const std::string& name) const
    {
        if (!m_folder_ready)
        {
            return;
        }
        std::ofstream out(m_folder / "_selected.txt", std::ios::binary | std::ios::trunc);
        out << (name.empty() ? std::string(kBuiltinName) : name) << "\n";
    }

    std::string Skin::remembered() const
    {
        if (!m_folder_ready)
        {
            return {};
        }
        std::ifstream in(m_folder / "_selected.txt", std::ios::binary);
        std::string line;
        if (in && std::getline(in, line))
        {
            while (!line.empty() && (line.back() == '\r' || line.back() == ' '))
            {
                line.pop_back();
            }
            return line;
        }
        return {};
    }

    uint64_t Skin::files_stamp() const
    {
        if (m_name.empty())
        {
            return 0;
        }
        const fs::path base = m_folder / path_from_utf8(m_name);
        uint64_t h = 1469598103934665603ull;
        auto mix = [&](const fs::path& p) {
            std::error_code ec;
            const auto t = fs::last_write_time(p, ec);
            const uint64_t stamp = ec ? 0 : static_cast<uint64_t>(t.time_since_epoch().count());
            const uint64_t size = ec ? 0 : static_cast<uint64_t>(fs::file_size(p, ec));
            h = (h ^ stamp) * 1099511628211ull;
            h = (h ^ size) * 1099511628211ull;
        };
        mix(base / "skin.json");
        std::set<std::string> files;
        for (const auto& [key, img] : m_spec.images)
        {
            files.insert(img.file);
        }
        if (!m_spec.font.empty())
        {
            files.insert(m_spec.font);
        }
        for (const std::string& f : files)
        {
            mix(base / path_from_utf8(f));
        }
        return h;
    }

    void Skin::clear_textures()
    {
        for (ImTextureData* t : m_textures)
        {
            if (t->Status == ImTextureStatus_WantCreate || t->Status == ImTextureStatus_Destroyed)
            {
                ImGui::UnregisterUserTexture(t); // never reached the backend
                IM_DELETE(t);
                continue;
            }
            t->SetStatus(ImTextureStatus_WantDestroy);
            t->UnusedFrames = 1; // backends destroy a texture once it has gone unused for a frame
            m_retired.push_back(t);
        }
        m_textures.clear();
        m_images.clear();
    }

    void Skin::drop_font()
    {
        if (m_font && ImGui::GetCurrentContext())
        {
            ImGui::GetIO().Fonts->RemoveFont(m_font);
        }
        m_font = nullptr;
    }

    void Skin::load_font(const fs::path& file)
    {
        std::ifstream in(file, std::ios::binary);
        if (!in)
        {
            m_problems.push_back("font: file not found");
            return;
        }
        std::vector<char> bytes((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
        if (bytes.size() < 12 || bytes.size() > (32u << 20))
        {
            m_problems.push_back("font: not a usable TTF/OTF file");
            return;
        }
        const unsigned char* b = reinterpret_cast<const unsigned char*>(bytes.data());
        const bool ttf = (b[0] == 0 && b[1] == 1 && b[2] == 0 && b[3] == 0) || std::memcmp(b, "OTTO", 4) == 0 || std::memcmp(b, "true", 4) == 0 ||
                         std::memcmp(b, "ttcf", 4) == 0;
        if (!ttf)
        {
            m_problems.push_back("font: not a TTF/OTF file");
            return;
        }
        ImGuiIO& io = ImGui::GetIO();
        void* data = IM_ALLOC(bytes.size());
        std::memcpy(data, bytes.data(), bytes.size());
        ImFontConfig cfg;
        cfg.FontDataOwnedByAtlas = true;
        const float size = io.Fonts->Fonts.Size > 0 ? io.Fonts->Fonts[0]->LegacySize : 19.0f;
        m_font = io.Fonts->AddFontFromMemoryTTF(data, static_cast<int>(bytes.size()), size, &cfg);
        if (!m_font)
        {
            m_problems.push_back("font: could not be loaded");
        }
    }

    bool Skin::load(const std::string& requested, std::string& message)
    {
        const bool builtin = requested.empty() || lower(requested) == lower(kBuiltinName);
        if (builtin)
        {
            clear_textures();
            drop_font();
            m_spec = {};
            m_name.clear();
            m_display = kBuiltinName;
            m_problems.clear();
            m_status = "built-in look";
            m_stamp = 0;
            resolve_roles();
            m_style_dirty = true;
            message = "Window skin: " + m_display;
            std::lock_guard guard(g_request_lock);
            g_active = kBuiltinName;
            return true;
        }

        // Match the folder name case-insensitively ("ubs skin rose glass").
        std::string name = requested;
        for (const std::string& n : available())
        {
            if (lower(n) == lower(requested))
            {
                name = n;
            }
        }
        const fs::path base = m_folder / path_from_utf8(name);
        std::string text;
        {
            std::ifstream in(base / "skin.json", std::ios::binary);
            if (!in)
            {
                message = "Skin '" + requested + "' was not found in " + path_to_utf8(m_folder);
                m_status = message;
                return false;
            }
            std::ostringstream ss;
            ss << in.rdbuf();
            text = ss.str();
        }
        SkinSpec spec;
        std::vector<std::string> warnings;
        std::string why;
        if (!parse_skin(text, spec, why, &warnings))
        {
            message = "Skin '" + name + "' not loaded: " + why;
            m_status = message;
            m_stamp = 0; // keep the current look; retry when the file changes
            return false;
        }

        clear_textures();
        drop_font();
        m_spec = std::move(spec);
        m_name = name;
        m_display = m_spec.name.empty() ? name : m_spec.name;
        m_problems = std::move(warnings);

        // Decode every file once, even when several keys share it.
        std::map<std::string, std::pair<ImTextureData*, ImVec2>> by_file;
        size_t loaded = 0;
        for (const auto& [key, spec_img] : m_spec.images)
        {
            auto it = by_file.find(spec_img.file);
            if (it == by_file.end())
            {
                Rgba8Image img;
                std::string error;
                ImTextureData* tex = nullptr;
                ImVec2 size{};
                if (decode_image_file(base / path_from_utf8(spec_img.file), img, error))
                {
                    shrink_to_fit(img, kMaxTextureSide);
                    bleed_transparent_edges(img);
                    tex = make_texture(img);
                    m_textures.push_back(tex);
                    size = ImVec2(static_cast<float>(img.width), static_cast<float>(img.height));
                    ++loaded;
                }
                else
                {
                    m_problems.push_back(spec_img.file + ": " + error);
                }
                it = by_file.emplace(spec_img.file, std::make_pair(tex, size)).first;
            }
            if (!it->second.first)
            {
                continue;
            }
            Image image;
            image.spec = spec_img;
            image.tex = it->second.first;
            image.width = static_cast<int>(it->second.second.x);
            image.height = static_cast<int>(it->second.second.y);
            if (image.spec.mode == ImageMode::Nine && image.spec.slice[0] + image.spec.slice[1] + image.spec.slice[2] + image.spec.slice[3] <= 0.0f)
            {
                const float s = std::floor(static_cast<float>(std::min(image.width, image.height)) / 3.0f);
                image.spec.slice[0] = image.spec.slice[1] = image.spec.slice[2] = image.spec.slice[3] = s;
            }
            m_images.emplace(key, image);
        }
        if (!m_spec.font.empty())
        {
            load_font(base / path_from_utf8(m_spec.font));
        }
        resolve_roles();
        m_stamp = files_stamp();
        m_style_dirty = true;
        m_status = "'" + m_display + "'" + (m_spec.author.empty() ? "" : " by " + m_spec.author) + ", " + std::to_string(loaded) + " image(s)";
        if (!m_problems.empty())
        {
            m_status += ", " + std::to_string(m_problems.size()) + " problem(s)";
        }
        message = "Window skin: " + m_status;
        std::lock_guard guard(g_request_lock);
        g_active = m_name;
        return true;
    }

    bool Skin::update()
    {
        bool changed = false;
        std::optional<std::pair<std::string, bool>> req;
        {
            std::lock_guard guard(g_request_lock);
            req.swap(g_request);
        }
        if (req)
        {
            std::string message;
            if (load(req->first, message) && req->second)
            {
                remember(m_name);
            }
            changed = true;
        }

        // Reload the active skin when its files change (skin authors see edits right away).
        const double now = std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count();
        if (!m_name.empty() && now >= m_next_check)
        {
            m_next_check = now + 1.0;
            const uint64_t stamp = files_stamp();
            if (stamp != m_stamp)
            {
                std::string message;
                load(m_name, message);
                m_stamp = stamp;
                changed = true;
            }
        }

        // Replaced textures: free them once the backend has let go.
        for (auto it = m_retired.begin(); it != m_retired.end();)
        {
            ImTextureData* t = *it;
            if (t->Status == ImTextureStatus_Destroyed)
            {
                ImGui::UnregisterUserTexture(t);
                IM_DELETE(t);
                it = m_retired.erase(it);
            }
            else
            {
                ++it;
            }
        }

        if (m_style_dirty)
        {
            m_style_dirty = false;
            changed = true;
        }
        return changed;
    }

    void Skin::shutdown()
    {
        for (ImTextureData* t : m_textures)
        {
            ImGui::UnregisterUserTexture(t);
            IM_DELETE(t);
        }
        for (ImTextureData* t : m_retired)
        {
            ImGui::UnregisterUserTexture(t);
            IM_DELETE(t);
        }
        m_textures.clear();
        m_retired.clear();
        m_images.clear();
        m_font = nullptr; // owned by the font atlas, which goes with the context
        m_split.ClearFreeMemory();
    }

    // ---------------------------------------------------------------- look

    void Skin::resolve_roles()
    {
        std::map<std::string, ImVec4> resolved;
        for (const ColorSlot& s : kColorSlots)
        {
            const auto given = m_spec.colors.find(s.key);
            if (given != m_spec.colors.end())
            {
                resolved[s.key] = given->second;
            }
            else if (s.ref)
            {
                resolved[s.key] = resolved[s.ref];
            }
            else if (!s.keep)
            {
                resolved[s.key] = s.value;
            }
        }
        m_roles[static_cast<size_t>(Role::Accent)] = resolved["accent"];
        m_roles[static_cast<size_t>(Role::AccentDim)] = resolved["accent_dim"];
        m_roles[static_cast<size_t>(Role::Good)] = resolved["good"];
        m_roles[static_cast<size_t>(Role::Warn)] = resolved["warn"];
        m_roles[static_cast<size_t>(Role::Muted)] = resolved["muted"];
        m_roles[static_cast<size_t>(Role::Title)] = resolved["title"];
        m_roles[static_cast<size_t>(Role::Text)] = resolved["text"];
        m_roles[static_cast<size_t>(Role::Window)] = resolved["window"];
    }

    void Skin::apply_style(float dpi)
    {
        m_dpi = dpi;
        resolve_roles();
        ImGuiStyle fresh;
        ImGuiStyle& style = ImGui::GetStyle();
        style = fresh;
        ImGui::StyleColorsDark(&style);

        for (const StyleSlot& s : kStyleSlots)
        {
            const auto given = m_spec.style.find(s.key);
            if (given == m_spec.style.end() && s.keep)
            {
                continue;
            }
            const ImVec2 v = given != m_spec.style.end() ? given->second : s.value;
            if (s.scalar)
            {
                style.*(s.scalar) = std::clamp(v.x, 0.0f, 64.0f);
            }
            else
            {
                style.*(s.vec) = ImVec2(std::clamp(v.x, 0.0f, 64.0f), std::clamp(v.y, 0.0f, 64.0f));
            }
        }

        std::map<std::string, ImVec4> resolved;
        for (const ColorSlot& s : kColorSlots)
        {
            const auto given = m_spec.colors.find(s.key);
            ImVec4 c;
            if (given != m_spec.colors.end())
            {
                c = given->second;
            }
            else if (s.ref)
            {
                c = resolved[s.ref];
            }
            else if (!s.keep)
            {
                c = s.value;
            }
            else
            {
                continue;
            }
            resolved[s.key] = c;
            if (s.col >= 0)
            {
                style.Colors[s.col] = c;
            }
        }
        for (const auto& [key, c] : m_spec.imgui_colors)
        {
            for (int i = 0; i < ImGuiCol_COUNT; ++i)
            {
                if (lower(ImGui::GetStyleColorName(i)) == key)
                {
                    style.Colors[i] = c;
                }
            }
        }

        style.ScaleAllSizes(dpi);
        style.FontScaleDpi = dpi;
        const auto fs_it = m_spec.style.find("font_scale");
        style.FontScaleMain = fs_it != m_spec.style.end() ? std::clamp(fs_it->second.x, 0.5f, 2.5f) : 1.0f;
    }

    uint32_t Skin::clear_rgb() const
    {
        const ImVec4& c = color(Role::Window);
        auto to8 = [](float f) { return static_cast<uint32_t>(std::lround(std::clamp(f, 0.0f, 1.0f) * 255.0f)); };
        return (to8(c.x) << 16) | (to8(c.y) << 8) | to8(c.z);
    }

    // ---------------------------------------------------------------- drawing

    const Skin::Image* Skin::find(std::string_view key) const
    {
        const auto it = m_images.find(key);
        return it == m_images.end() ? nullptr : &it->second;
    }

    bool Skin::has_image(std::string_view key) const
    {
        return find(key) != nullptr;
    }

    bool Skin::has_icon(std::string_view key) const
    {
        return !key.empty() && find("icon." + lower(key)) != nullptr;
    }

    void Skin::draw_image(ImDrawList* dl, std::string_view key, ImVec2 a, ImVec2 b, float alpha) const
    {
        if (const Image* img = find(key))
        {
            draw(dl, *img, a, b, alpha);
        }
    }

    void Skin::draw(ImDrawList* dl, const Image& img, ImVec2 a, ImVec2 b, float alpha) const
    {
        if (!img.tex || img.width <= 0 || img.height <= 0 || b.x <= a.x || b.y <= a.y)
        {
            return;
        }
        const ImTextureRef ref = img.tex->GetTexRef();
        const ImU32 col = tint_color(img.spec.tint, alpha * ImGui::GetStyle().Alpha);
        const float W = b.x - a.x, H = b.y - a.y;
        const float iw = static_cast<float>(img.width), ih = static_cast<float>(img.height);
        switch (img.spec.mode)
        {
        case ImageMode::Stretch:
            dl->AddImage(ref, a, b, ImVec2(0, 0), ImVec2(1, 1), col);
            break;
        case ImageMode::Cover: {
            const float s = std::max(W / iw, H / ih);
            const float uw = W / (iw * s), vh = H / (ih * s);
            dl->AddImage(ref, a, b, ImVec2((1.0f - uw) * 0.5f, (1.0f - vh) * 0.5f), ImVec2((1.0f + uw) * 0.5f, (1.0f + vh) * 0.5f), col);
            break;
        }
        case ImageMode::Contain: {
            const float s = std::min(W / iw, H / ih);
            const ImVec2 size(iw * s, ih * s);
            const ImVec2 p(snap(a.x + (W - size.x) * 0.5f), snap(a.y + (H - size.y) * 0.5f));
            dl->AddImage(ref, p, ImVec2(p.x + snap(size.x), p.y + snap(size.y)), ImVec2(0, 0), ImVec2(1, 1), col);
            break;
        }
        case ImageMode::Center: {
            const float s = img.spec.scale * m_dpi;
            const ImVec2 size(snap(iw * s), snap(ih * s));
            const ImVec2 p(snap(a.x + (W - size.x) * 0.5f), snap(a.y + (H - size.y) * 0.5f));
            dl->PushClipRect(a, b, true);
            dl->AddImage(ref, p, ImVec2(p.x + size.x, p.y + size.y), ImVec2(0, 0), ImVec2(1, 1), col);
            dl->PopClipRect();
            break;
        }
        case ImageMode::Tile: {
            const float s = img.spec.scale * m_dpi;
            const float tw = std::max(4.0f, snap(iw * s)), th = std::max(4.0f, snap(ih * s));
            const int nx = static_cast<int>(std::ceil(W / tw)), ny = static_cast<int>(std::ceil(H / th));
            if (nx * ny > 2500)
            {
                dl->AddImage(ref, a, b, ImVec2(0, 0), ImVec2(W / tw, H / th), col); // falls back to one stretched quad
                break;
            }
            dl->PushClipRect(a, b, true);
            for (int y = 0; y < ny; ++y)
            {
                for (int x = 0; x < nx; ++x)
                {
                    const ImVec2 p(snap(a.x) + tw * static_cast<float>(x), snap(a.y) + th * static_cast<float>(y));
                    dl->AddImage(ref, p, ImVec2(p.x + tw, p.y + th), ImVec2(0, 0), ImVec2(1, 1), col);
                }
            }
            dl->PopClipRect();
            break;
        }
        case ImageMode::Nine: {
            const float s = img.spec.scale * m_dpi;
            float l = img.spec.slice[0] * s, t = img.spec.slice[1] * s, r = img.spec.slice[2] * s, bt = img.spec.slice[3] * s;
            // Borders shrink together when the area is smaller than they are.
            if (l + r > W && l + r > 0.0f)
            {
                const float k = W / (l + r);
                l *= k, r *= k;
            }
            if (t + bt > H && t + bt > 0.0f)
            {
                const float k = H / (t + bt);
                t *= k, bt *= k;
            }
            const float x[4] = {snap(a.x), snap(a.x + l), snap(b.x - r), snap(b.x)};
            const float y[4] = {snap(a.y), snap(a.y + t), snap(b.y - bt), snap(b.y)};
            const float u[4] = {0.0f, img.spec.slice[0] / iw, 1.0f - img.spec.slice[2] / iw, 1.0f};
            const float v[4] = {0.0f, img.spec.slice[1] / ih, 1.0f - img.spec.slice[3] / ih, 1.0f};
            for (int j = 0; j < 3; ++j)
            {
                for (int i = 0; i < 3; ++i)
                {
                    if (x[i + 1] > x[i] && y[j + 1] > y[j] && u[i + 1] > u[i] && v[j + 1] > v[j])
                    {
                        dl->AddImage(ref, ImVec2(x[i], y[j]), ImVec2(x[i + 1], y[j + 1]), ImVec2(u[i], v[j]), ImVec2(u[i + 1], v[j + 1]), col);
                    }
                }
            }
            break;
        }
        }
    }

    // Splits the current window's draw list so an image can be drawn *under* the next widget
    // after the widget has been laid out (its rectangle and hover state are known then).
    // Never nested: each helper uses it around exactly one widget.
    class Skin::Underlay
    {
      public:
        Underlay(Skin& skin, bool active) : m_skin(skin), m_active(active)
        {
            if (m_active)
            {
                m_dl = ImGui::GetWindowDrawList();
                m_skin.m_split.Split(m_dl, 2);
                m_skin.m_split.SetCurrentChannel(m_dl, 1);
            }
        }
        ImDrawList* back()
        {
            m_skin.m_split.SetCurrentChannel(m_dl, 0);
            return m_dl;
        }
        void finish()
        {
            if (m_active)
            {
                m_skin.m_split.Merge(m_dl);
                m_active = false;
            }
        }
        ~Underlay() { finish(); }

      private:
        Skin& m_skin;
        bool m_active;
        ImDrawList* m_dl{};
    };

    void Skin::draw_window_background()
    {
        if (const Image* img = find("background"))
        {
            const ImVec2 p = ImGui::GetWindowPos(), s = ImGui::GetWindowSize();
            draw(ImGui::GetWindowDrawList(), *img, p, ImVec2(p.x + s.x, p.y + s.y), 1.0f);
        }
    }

    void Skin::draw_header_strip(float row_height)
    {
        if (const Image* img = find("header"))
        {
            if (find("logo")) // the title row is as tall as the logo
            {
                const auto lh = m_spec.style.find("logo_height");
                row_height = std::max(row_height, snap(ImGui::GetFontSize() * (lh != m_spec.style.end() ? std::clamp(lh->second.x, 0.5f, 6.0f) : 1.6f)));
            }
            const ImVec2 wp = ImGui::GetWindowPos();
            const float bottom = ImGui::GetCursorScreenPos().y + row_height + ImGui::GetStyle().ItemSpacing.y * 0.5f;
            draw(ImGui::GetWindowDrawList(), *img, wp, ImVec2(wp.x + ImGui::GetWindowWidth(), snap(bottom)), 1.0f);
        }
    }

    bool Skin::logo(float height)
    {
        const Image* img = find("logo");
        if (!img)
        {
            return false;
        }
        const auto lh = m_spec.style.find("logo_height");
        const float h = snap(height * (lh != m_spec.style.end() ? std::clamp(lh->second.x, 0.5f, 6.0f) : 1.6f));
        const float w = std::min(snap(h * static_cast<float>(img->width) / static_cast<float>(img->height)), ImGui::GetContentRegionAvail().x * 0.6f);
        const ImVec2 p = ImGui::GetCursorScreenPos();
        draw(ImGui::GetWindowDrawList(), *img, p, ImVec2(p.x + w, p.y + h), 1.0f);
        ImGui::Dummy(ImVec2(w, h));
        return true;
    }

    bool Skin::icon(std::string_view key, float size)
    {
        if (key.empty())
        {
            return false;
        }
        const Image* img = find("icon." + lower(key));
        if (!img)
        {
            return false;
        }
        const ImVec2 p = ImGui::GetCursorScreenPos();
        const float frame = ImGui::GetFrameHeight();
        const float y = p.y + std::max(0.0f, (frame - size) * 0.5f);
        draw(ImGui::GetWindowDrawList(), *img, ImVec2(p.x, y), ImVec2(p.x + size, y + size), 1.0f);
        ImGui::Dummy(ImVec2(size, std::min(size, frame)));
        ImGui::SameLine();
        return true;
    }

    namespace
    {
        // Leading spaces that leave room for an icon inside a button or tab label.
        std::string with_icon_room(const char* label, float icon_w)
        {
            const float space = std::max(1.0f, ImGui::CalcTextSize(" ").x);
            const int n = static_cast<int>(std::ceil(icon_w / space));
            return std::string(static_cast<size_t>(n), ' ') + label;
        }

        bool visible_text(const char* label)
        {
            return label && label[0] && !(label[0] == '#' && label[1] == '#');
        }

        void push_clear(std::initializer_list<ImGuiCol> cols)
        {
            for (ImGuiCol c : cols)
            {
                ImGui::PushStyleColor(c, ImVec4(0, 0, 0, 0));
            }
        }
    } // namespace

    bool Skin::button(const char* label, std::string_view icon_key, const ImVec2& size)
    {
        const Image* normal = find("button");
        const Image* ic = icon_key.empty() ? nullptr : find("icon." + lower(icon_key));
        const float icon_w = ImGui::GetFontSize();
        std::string padded;
        const char* text = label;
        ImVec2 sz = size;
        if (ic)
        {
            if (visible_text(label))
            {
                padded = with_icon_room(label, icon_w + ImGui::GetStyle().ItemInnerSpacing.x * 0.5f);
                text = padded.c_str();
            }
            else if (sz.x <= 0.0f)
            {
                sz = ImVec2(icon_w + ImGui::GetStyle().FramePadding.x * 2.0f, 0.0f);
            }
        }
        bool pressed = false;
        {
            Underlay under(*this, normal != nullptr);
            if (normal)
            {
                push_clear({ImGuiCol_Button, ImGuiCol_ButtonHovered, ImGuiCol_ButtonActive});
            }
            pressed = ImGui::Button(text, sz);
            if (normal)
            {
                ImGui::PopStyleColor(3);
                const Image* img = normal;
                if (ImGui::IsItemActive() && find("button_active"))
                {
                    img = find("button_active");
                }
                else if (ImGui::IsItemHovered() && find("button_hover"))
                {
                    img = find("button_hover");
                }
                draw(under.back(), *img, ImGui::GetItemRectMin(), ImGui::GetItemRectMax(), 1.0f);
            }
        }
        if (ic)
        {
            const ImVec2 a = ImGui::GetItemRectMin(), b = ImGui::GetItemRectMax();
            const float h = b.y - a.y;
            const float x = visible_text(label) ? a.x + ImGui::GetStyle().FramePadding.x : a.x + (b.x - a.x - icon_w) * 0.5f;
            const float y = a.y + (h - icon_w) * 0.5f;
            draw(ImGui::GetWindowDrawList(), *ic, ImVec2(snap(x), snap(y)), ImVec2(snap(x) + icon_w, snap(y) + icon_w), 1.0f);
        }
        return pressed;
    }

    float Skin::button_width(const char* label, std::string_view icon_key) const
    {
        const ImGuiStyle& style = ImGui::GetStyle();
        const bool ic = !icon_key.empty() && find("icon." + lower(icon_key)) != nullptr;
        if (ic && !visible_text(label))
        {
            return ImGui::GetFontSize() + style.FramePadding.x * 2.0f;
        }
        const char* shown = label;
        std::string padded;
        if (ic)
        {
            padded = with_icon_room(label, ImGui::GetFontSize() + style.ItemInnerSpacing.x * 0.5f);
            shown = padded.c_str();
        }
        return ImGui::CalcTextSize(shown, nullptr, true).x + style.FramePadding.x * 2.0f;
    }

    bool Skin::small_button(const char* label)
    {
        const Image* normal = find("button");
        Underlay under(*this, normal != nullptr);
        if (normal)
        {
            push_clear({ImGuiCol_Button, ImGuiCol_ButtonHovered, ImGuiCol_ButtonActive});
        }
        const bool pressed = ImGui::SmallButton(label);
        if (normal)
        {
            ImGui::PopStyleColor(3);
            const Image* img = normal;
            if (ImGui::IsItemActive() && find("button_active"))
            {
                img = find("button_active");
            }
            else if (ImGui::IsItemHovered() && find("button_hover"))
            {
                img = find("button_hover");
            }
            draw(under.back(), *img, ImGui::GetItemRectMin(), ImGui::GetItemRectMax(), 1.0f);
        }
        return pressed;
    }

    bool Skin::slider_float(const char* label, float* v, float lo, float hi, const char* format, ImGuiSliderFlags flags)
    {
        const Image* track = find("slider_track");
        const Image* fill = find("slider_fill");
        const Image* grab = find("slider_grab");
        const Image* grab_active = find("slider_grab_active");
        if (!track && !fill && !grab)
        {
            return ImGui::SliderFloat(label, v, lo, hi, format, flags);
        }
        const float frame_w = ImGui::CalcItemWidth(); // what SliderFloat will use (SetNextItemWidth included)
        const float frame_h = ImGui::GetFrameHeight();
        Underlay under(*this, true);
        push_clear({ImGuiCol_FrameBg, ImGuiCol_FrameBgHovered, ImGuiCol_FrameBgActive, ImGuiCol_SliderGrab, ImGuiCol_SliderGrabActive});
        const bool changed = ImGui::SliderFloat(label, v, lo, hi, format, flags);
        ImGui::PopStyleColor(5);

        const bool hovered = ImGui::IsItemHovered();
        const bool active = ImGui::IsItemActive();
        const ImGuiStyle& style = ImGui::GetStyle();
        const ImVec2 a = ImGui::GetItemRectMin();
        const ImVec2 b(a.x + frame_w, a.y + frame_h);
        ImDrawList* dl = under.back();

        // Track: image, or the skin's frame colour (the widget's own frame is hidden).
        if (track)
        {
            draw(dl, *track, a, b, 1.0f);
        }
        else
        {
            const ImGuiCol c = active ? ImGuiCol_FrameBgActive : hovered ? ImGuiCol_FrameBgHovered : ImGuiCol_FrameBg;
            dl->AddRectFilled(a, b, ImGui::GetColorU32(c), style.FrameRounding);
        }

        // Same grab geometry as Dear ImGui's SliderBehavior for float sliders.
        float t = 0.0f;
        const float value = std::isfinite(*v) ? *v : lo;
        if ((flags & ImGuiSliderFlags_Logarithmic) && lo > 0.0f && hi > lo)
        {
            t = std::log(std::clamp(value, lo, hi) / lo) / std::log(hi / lo);
        }
        else if (hi != lo)
        {
            t = (std::clamp(value, std::min(lo, hi), std::max(lo, hi)) - lo) / (hi - lo);
        }
        t = std::clamp(t, 0.0f, 1.0f);
        const float pad = 2.0f;
        const float slider_sz = frame_w - pad * 2.0f;
        const float grab_sz = std::min(style.GrabMinSize, slider_sz);
        const float usable_min = a.x + pad + grab_sz * 0.5f;
        const float usable_max = b.x - pad - grab_sz * 0.5f;
        const float gx = usable_min + (usable_max - usable_min) * t;

        if (fill && gx > a.x)
        {
            dl->PushClipRect(a, ImVec2(snap(gx), b.y), true);
            draw(dl, *fill, a, b, 1.0f); // the whole fill image, cut at the grab
            dl->PopClipRect();
        }
        const Image* g = active && grab_active ? grab_active : grab;
        if (g)
        {
            const float gh = frame_h;
            const float gw = std::max(grab_sz, gh * static_cast<float>(g->width) / static_cast<float>(g->height));
            const float gx0 = snap(gx - gw * 0.5f);
            draw(dl, *g, ImVec2(gx0, a.y), ImVec2(gx0 + snap(gw), b.y), 1.0f);

            // An image grab can be bigger and brighter than Dear ImGui's thin bar, and the value is
            // printed in the middle of the slider: where they overlap, the text gets a dark outline
            // (drawn here, above the grab and below the widget's own text).
            char text[64];
            std::snprintf(text, sizeof(text), format && *format ? format : "%.3f", static_cast<double>(*v));
            const ImVec2 ts = ImGui::CalcTextSize(text);
            const float cx = (a.x + b.x) * 0.5f, cy = (a.y + b.y) * 0.5f;
            const ImVec2 tp(std::floor(cx - ts.x * 0.5f), std::floor(cy - ts.y * 0.5f)); // same spot as RenderTextClipped centres it
            if (gx0 < tp.x + ts.x && gx0 + gw > tp.x)
            {
                const ImU32 dark = IM_COL32(0, 0, 0, static_cast<int>(200 * style.Alpha));
                const float o = std::max(1.0f, std::floor(m_dpi + 0.25f));
                static const float dirs[8][2] = {{-1, -1}, {0, -1}, {1, -1}, {-1, 0}, {1, 0}, {-1, 1}, {0, 1}, {1, 1}};
                dl->PushClipRect(a, b, true);
                for (const auto& d : dirs)
                {
                    dl->AddText(ImVec2(tp.x + d[0] * o, tp.y + d[1] * o), dark, text);
                }
                dl->PopClipRect();
            }
        }
        else
        {
            dl->AddRectFilled(ImVec2(gx - grab_sz * 0.5f, a.y + pad), ImVec2(gx + grab_sz * 0.5f, b.y - pad),
                              ImGui::GetColorU32(active ? ImGuiCol_SliderGrabActive : ImGuiCol_SliderGrab), style.GrabRounding);
        }
        return changed;
    }

    bool Skin::checkbox(const char* label, bool* v)
    {
        const Image* off = find("checkbox");
        const Image* on = find("checkbox_checked");
        if (!off && !on)
        {
            return ImGui::Checkbox(label, v);
        }
        Underlay under(*this, true);
        push_clear({ImGuiCol_FrameBg, ImGuiCol_FrameBgHovered, ImGuiCol_FrameBgActive});
        if (on)
        {
            ImGui::PushStyleColor(ImGuiCol_CheckMark, ImVec4(0, 0, 0, 0));
        }
        const bool changed = ImGui::Checkbox(label, v);
        ImGui::PopStyleColor(on ? 4 : 3);
        const float s = ImGui::GetFrameHeight();
        const ImVec2 a = ImGui::GetItemRectMin();
        const ImVec2 b(a.x + s, a.y + s);
        ImDrawList* dl = under.back();
        const Image* img = (*v && on) ? on : off;
        if (img)
        {
            draw(dl, *img, a, b, 1.0f);
        }
        else
        {
            dl->AddRectFilled(a, b, ImGui::GetColorU32(ImGui::IsItemHovered() ? ImGuiCol_FrameBgHovered : ImGuiCol_FrameBg), ImGui::GetStyle().FrameRounding);
        }
        return changed;
    }

    bool Skin::begin_tab_item(const char* label, std::string_view icon_key, ImGuiTabItemFlags flags)
    {
        const Image* tab = find("tab");
        const Image* hover = find("tab_hover");
        const Image* selected = find("tab_active");
        const Image* ic = icon_key.empty() ? nullptr : find("icon." + lower(icon_key));
        const float icon_w = ImGui::GetFontSize();
        std::string padded;
        const char* text = label;
        if (ic)
        {
            padded = with_icon_room(label, icon_w + ImGui::GetStyle().ItemInnerSpacing.x * 0.5f);
            // Keep the tab's ID independent of the icon so switching skins keeps the open tab.
            if (!std::strstr(label, "###"))
            {
                padded += "###";
                padded += label;
            }
            text = padded.c_str();
        }
        const bool images = tab || hover || selected;
        bool open = false;
        {
            Underlay under(*this, images);
            if (images)
            {
                push_clear({ImGuiCol_Tab, ImGuiCol_TabHovered, ImGuiCol_TabSelected, ImGuiCol_TabSelectedOverline, ImGuiCol_TabDimmed,
                            ImGuiCol_TabDimmedSelected, ImGuiCol_TabDimmedSelectedOverline});
            }
            open = ImGui::BeginTabItem(text, nullptr, flags);
            if (images)
            {
                ImGui::PopStyleColor(7);
                const bool hovered = ImGui::IsItemHovered();
                const Image* img = open ? (selected ? selected : tab) : hovered ? (hover ? hover : tab) : tab;
                const ImVec2 a = ImGui::GetItemRectMin(), b = ImGui::GetItemRectMax();
                if (img)
                {
                    draw(under.back(), *img, a, b, 1.0f);
                }
                else // this state has no image: the skin's tab colour instead
                {
                    const ImGuiCol c = open ? ImGuiCol_TabSelected : hovered ? ImGuiCol_TabHovered : ImGuiCol_Tab;
                    under.back()->AddRectFilled(a, b, ImGui::GetColorU32(c), ImGui::GetStyle().TabRounding, ImDrawFlags_RoundCornersTop);
                }
            }
        }
        if (ic)
        {
            const ImVec2 a = ImGui::GetItemRectMin(), b = ImGui::GetItemRectMax();
            const float x = snap(a.x + ImGui::GetStyle().FramePadding.x);
            const float y = snap(a.y + (b.y - a.y - icon_w) * 0.5f);
            // Tabs clip their own contents; draw on the tab bar's list, inside the tab.
            ImDrawList* dl = ImGui::GetWindowDrawList();
            dl->PushClipRect(a, b, true);
            draw(dl, *ic, ImVec2(x, y), ImVec2(x + icon_w, y + icon_w), 1.0f);
            dl->PopClipRect();
        }
        return open;
    }

    bool Skin::begin_child(const char* id, const ImVec2& size, ImGuiChildFlags flags)
    {
        const Image* panel = find("panel");
        if (!panel)
        {
            return ImGui::BeginChild(id, size, flags);
        }
        ImGui::PushStyleColor(ImGuiCol_ChildBg, ImVec4(0, 0, 0, 0));
        const bool open = ImGui::BeginChild(id, size, flags);
        ImGui::PopStyleColor();
        const ImVec2 p = ImGui::GetWindowPos(), s = ImGui::GetWindowSize();
        draw(ImGui::GetWindowDrawList(), *panel, p, ImVec2(p.x + s.x, p.y + s.y), 1.0f);
        return open;
    }

    void Skin::end_child()
    {
        ImGui::EndChild();
    }
} // namespace uuepbs::ui
